package my.demo.dao.user;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import my.demo.entity.User;
import my.demo.entity.UserAccount;

@Mapper
public interface UserDao {
	@Select("select * from usr_user_account where account=#{account} and account_hash=#{accountHash}")
	@ResultMap("userAccount")
	UserAccount getUserAccount(@Param("account") String account, @Param("accountHash") int accountHash);
	
	@Insert("insert into usr_user_account(account, password, user_id, account_hash) values (#{account}, #{password}, #{userId}, #{accountHash})")
	int createUserAccount(UserAccount userAccount);
	
	@Select("select * from usr_user where user_id=#{userId}")
	@ResultMap("user")
	User getUser(long userId);
	
	/**
	 * ATTENTION:
	 * <ol>
	 * <li>Without Mycat and Sharding-Proxy, user_id is generated by MySQL auto increment, both <code>last_insert_id()</code> and <code>GENERATED_KEY</code> can be used to get last inserted value;</li>
	 * <li>With Mycat, user_id is generated by Mycat global sequence, both <code>last_insert_id()</code> and <code>GENERATED_KEY</code> can be used to get last inserted value, see docs/Sharding-Mycat-Overview-Quickstart.md;</li>
	 * <li>With Sharding-Proxy, user_id is generated by Sharding-Proxy, <code>GENERATED_KEY</code> is the only way to get last inserted value, see docs/Sharding-Sharding-Proxy-Overview-Quickstart.md;</li>
	 * </ol> 
	 * @param user
	 * @return
	 */
	@Insert("insert into usr_user (nickname, mobile, email, created_at) values (#{nickname}, #{mobile}, #{email}, #{createdAt})")
	@Options(useGeneratedKeys=true, keyProperty="userId", keyColumn="user_id")
	int createUser(User user);
}