FROM mydemo/openjdk:8-jre-alpine

WORKDIR /home
ENV MYSQL_HOST=mysql NACOS_HOST=nacos ZIPKIN_HOST=zipkin SERVICE_PORT=20880
ADD ./target/order-service-0.0.1-SNAPSHOT.jar /home/
EXPOSE 20880
ENTRYPOINT ["java", "-jar", "/home/order-service-0.0.1-SNAPSHOT.jar"]