FROM mydemo/openjdk:8-jre-alpine

WORKDIR /home
ENV NACOS_HOST=nacos ZIPKIN_HOST=zipkin SERVICE_PORT=20880
ADD ./target/item-service-0.0.1-SNAPSHOT.jar /home/
EXPOSE $SERVICE_PORT
ENTRYPOINT ["java", "-jar", "/home/item-service-0.0.1-SNAPSHOT.jar"]