FROM mydemo/openjdk:8-jre-alpine

WORKDIR /home
ENV NACOS_HOST=nacos ZIPKIN_HOST=zipkin SERVICE_PORT=8090
ADD ./target/shop-web-0.0.1-SNAPSHOT.jar /home/
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "/home/shop-web-0.0.1-SNAPSHOT.jar"]